#! /bin/zsh
reset

SRC="source/"

LIST=(
    "missingIncludeSystem"
    "missingInclude"
    "useStlAlgorithm"
    "checkersReport"
)

WARNINGS=$(printf "--suppress=%s " "${LIST[@]}")

CMD="cppcheck $SRC --enable=all $WARNINGS $SRC --std=c++23 --check-level=exhaustive"
eval ${CMD}