#! /bin/zsh

TEST_ROOT="$HOME/dev/projects/cpp/personal/writing-a-c-compiler-tests"
TEST_SCRIPT="test_compiler"
TEST_CHAPTER="--chapter 1"
TEST_STAGE="lex"
CMD="$TEST_ROOT/$TEST_SCRIPT $(which wacc) $TEST_CHAPTER --stage $TEST_STAGE"

echo "🧪 - Testing compiler..."
eval ${CMD}