#! /bin/zsh

TEST_ROOT="$HOME/dev/projects/cpp/personal/writing-a-c-compiler-tests"
TEST_SCRIPT="test_compiler"
TEST_CHAPTER="--chapter 2"
CMD="$TEST_ROOT/$TEST_SCRIPT $(which wacc) $TEST_CHAPTER"

echo "🧪 - Testing compiler..."
eval ${CMD}